### ISSUE TITLE
Download file contains only `undefined`

### ISSUE THREAD

**Issue by regseb** [fregante/bundle#1]
Hi,

When I download the [bundle of _content-scripts-register-polyfill_](https://bundle.fregante.com/?pkg=content-scripts-register-polyfill), the file contains only `undefined`.

The _textarea_ in the page seems to have the complete file:

```JavaScript
(function () {
	'use strict';

	// [...]

	if (typeof chrome === 'object' && !chrome.contentScripts) {
	    chrome.contentScripts = { register: registerContentScript };
	}

}());

```

**Comment by fregante** [comment]
Thanks for the report! What browser are you using?

**Comment by regseb** [comment]
I have the problem with Firefox 92 and Chrome 94.

I think the problem is in [this line](https://github.com/fregante/bundle/blob/main/public/loader.js#L33): `const blob = new Blob([output.bundle], {`
The variable `output` is a string and doesn't have property `bundle`. Maybe, you should write : `const blob = new Blob([output], {`

**Comment by fregante** [comment]
Ahhh it's been broken for 7 months 😅 

https://github.com/fregante/bundle/commit/5364b83d9552f2e87412191650932281fdab6f39

Could send a PR? If not, I might fix it later
